19 - USER ACCOUNTS/19-2. Blog Accounts/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

19 - USER ACCOUNTS/19-2. Blog Accounts/blogs/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page for adding a post
    path('new_post/', views.new_post, name='new_post'),
    # Page for editing an entry.
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

19 - USER ACCOUNTS/19-2. Blog Accounts/users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

19 - USER ACCOUNTS/19-2. Blog Accounts/blogs/models.py
from django.db import models

class BlogPost(models.Model):
    title = models.CharField(max_length=256)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.title} - {self.text}'

19 - USER ACCOUNTS/19-2. Blog Accounts/users/models.py
from django.db import models

# Create your models here.

19 - USER ACCOUNTS/19-2. Blog Accounts/blogs/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django import forms

from .models import BlogPost
        
class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

19 - USER ACCOUNTS/19-2. Blog Accounts/blogs/views.py
from django.shortcuts import render, redirect

from .models import BlogPost
from .forms import BlogPostForm

def index(request):
    posts = BlogPost.objects.order_by('date_added')
    context = {'posts': posts}
    return render(request, 'blogs/index.html', context)

def new_post(request):
    if request.method != 'POST':
        form = BlogPostForm()
    else:
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
        
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

def edit_post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    
    if request.method != 'POST':
        form = BlogPostForm(instance=post)
    else:
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
        
    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

19 - USER ACCOUNTS/19-2. Blog Accounts/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

19 - USER ACCOUNTS/19-2. Blog Accounts/blogs/templates/blogs/base.html
<p>
    <a href="{% url 'blogs:index' %}">Blogs</a> -
    <a href="{% url 'blogs:new_post' %}">Add a post</a> -
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a> -
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>
{% block content %}{% endblock content %}

19 - USER ACCOUNTS/19-2. Blog Accounts/blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>Edit post:</p>
    
    <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

19 - USER ACCOUNTS/19-2. Blog Accounts/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
    
    <ul>
        {% for post in posts %}
            <p>{{ post|linebreaks }}</p>
            <p>
                <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a>
            </p>
        {% empty %}
            <p>No posts added yet</p>
        {% endfor %}
    </ul>
    
{% endblock content %}

19 - USER ACCOUNTS/19-2. Blog Accounts/blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>Add a post:</p>
    
    <form action="{% url 'blogs:new_post' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add post</button>
    </form>

{% endblock content %}